### ISSUE TITLE
Cannot reproduce

### ISSUE THREAD

**Issue by dad616610** [barbariansubhkaran/Shell-and-Tube-Heat-exchanger-OpenFOAM#1]
I tried to reproduce the shell and heat exchanger with the files in the repo, but failed

The last step (`foamJob -parallel -screen  chtMultiRegionSimpleFoam`) fails with the following error:
```
[2] --> FOAM FATAL ERROR: (openfoam-2306)
[2] Incorrect patch type wall for patch inlet_baffle of field T in file "./Shell-and-Tube-Heat-exchanger-OpenFOAM/processor2/0/hot/T"
Type should be a mappedPatch
[2] 
[2]     From static const Foam::mappedPatchBase& Foam::mappedPatchFieldBase<Type>::mapper(const Foam::fvPatch&, const Foam::DimensionedField<Type, Foam::volMesh>&) [with Type = double]
[2]     in file ./src/finiteVolume/lnInclude/mappedPatchFieldBase.C at line 962.
[2] 
FOAM parallel run exiting
```

I'm using OpenFoam v.2306. Might the error be due to using different OpenFoam versions?
The result I got till the last step can be found in my fork of this repo: [here](https://github.com/dad616610/Shell-and-Tube-heater)

Could you please upload all the files up-to the last step? I could then compare them with my files to try to pinpoint the source of the error. 
To upload my big files, I used `git lfs` ([tutorial](https://castorfou.github.io/guillaume_blog/blog/push-big-files-to-github.html#Solution:-git-lfs)). They're not viewable in GitHub, but one can clone the repo and view them locally.
Maybe you could suggest some solutions \ useful links to help to resolve this issue?

In any case, thanks for providing the files!

**Comment by barbariansubhkaran** [comment]
Hello, 

I found the problem. It just needs a simple change in the boundary file. I will do it and send you back.

**Comment by barbariansubhkaran** [comment]
https://github.com/barbariansubhkaran/Shell-and-Tube-Heat-exchanger-OpenFOAM 

I made the changes, check if it is working now.

**Comment by barbariansubhkaran** [comment]
Hello, I checked and it is working.
